### ISSUE TITLE
Exception calling application: module 'gym.envs.box2d' has no attribute 'LunarLander'

### ISSUE THREAD

**Issue by dtitov** [aunum/gold#12]
It seems that the only working environment is `CartPole-v1`. If I try to use `LunarLander-v2` or something else from Box2D, I get an error, for example:
```
	server, err := env.FindOrCreate(env.GymServerConfig)
	if err != nil {
		log.Fatal(err)
	}
	defer server.Close()

	environment, err = server.Make("LunarLander-v2", env.WithRecorder())
	if err != nil {
		log.Fatal(err)
	}
```

Error: 
```
2020/04/10 18:15:13 rpc error: code = Unknown desc = Exception calling application: module 'gym.envs.box2d' has no attribute 'LunarLander'
```

I wonder whether it's expected behavior or not? Should I perform some extra steps to enable additional environments?

**Comment by pbarker** [comment]
Haven't tried lunar lander yet, let me see whats going on here

**Comment by pbarker** [comment]
Ok just needed to add some deps over in https://github.com/aunum/sphere if you pull the latest `sphereproject/gym` docker image it should load. Let me know if you have any trouble.

**Comment by dtitov** [comment]
Works, thanks :)
