### ISSUE TITLE
Cannot convert FauxZero

### ISSUE THREAD

**Issue by JetSetIlly** [aunum/gold#2]
Cloned repository and using the quick start instructions.

 $ go run ./pkg/v1/agent/deepq/experiments/cartpole/main.go
 \# github.com/aunum/gold/pkg/v1/dense
 pkg/v1/dense/value.go:57:19: cannot convert FauxZero (type float64) to type complex64
 pkg/v1/dense/value.go:59:20: cannot convert FauxZero (type float64) to type complex128

Using go v1.14 on linux/amd64

**Comment by pbarker** [comment]
Thanks for catching that, just updated from go 13.6 to 14.1 and reproduced, let me dig in and see what changed recently

**Comment by pbarker** [comment]
Pushed a hot fix, thats a breaking change on Go's end, I'll need to see if this is intended.

**Comment by JetSetIlly** [comment]
Possible fix if it is an intended change in go. Define FauxZero without the explicit cast.

const FauxZero = 1e-6

That said, it looks like a bug in Go to me. I don't see any reason why they would break that functionality intentionally.

**Comment by JetSetIlly** [comment]
I had a quick look through the Go source and I tracked it down to the typecheck1() function, specifically line 1630 of the typecheck.go file in go/src/cmd/compile/internal/gc

		n.Left = convlit1(n.Left, n.Type, true, nil)

Compare to 1.13.6 this is different. I think the problem must be in there. Looking into convlit1() it's changed quite a bit since the earlier version but I don't know the system well enough to proceed so I'll leave it for now.

**Comment by JetSetIlly** [comment]
Okay, I think this is a fix. It's an additional test in convertop() saying that if we're converting from float to complex then it's okay.

https://github.com/JetSetIlly/go/commit/0ce0e5bf4ddc7dde0dacf794ab5f6e832eb41168

I've been testing with this:

> package main
> 
> import "fmt"
>
> const foo = 1.0
> const bar = float64(1.0)
>
> func main() {
>	cmplxFoo := complex64(foo)
>	fmt.Println(cmplxFoo)
>	cmplxBar := complex64(bar)
>	fmt.Println(cmplxBar)
>	fmt.Println(cmplxFoo == cmplxBar)
>}

**Comment by pbarker** [comment]
yup I ran into the constant thing late last night too, very strange, asked in gopher slack and no one knew.  In python, you can convert between a float and a complex where the complex just has a real part of the float and an imaginary part of zero. I would need to read deeper into Go types on their philosophy here.

**Comment by JetSetIlly** [comment]
This has worried me enough to ask on the golang-nuts mailing list. The answer from of the Go developers is that while conversion from int/float variable to complex variables is not supported at all (both 1.13.6 and 1.14 behave correctly in this regard) the spec is not as clear cut about conversion from a typed constant.

I'm going to open up an issue on the Go repository about this unintended change between 1.13.6 and 1.14

I think the best solution for Gold would be to just use the complex() function:

>	case reflect.Complex64:
>		return complex(FauxZero, 0)
>	case reflect.Complex128:
>		return complex(FauxZero, 0)
>	default:

**Comment by JetSetIlly** [comment]
This is the change that fixes the compiler bug:

https://go-review.googlesource.com/c/go/+/226197/

It'll be part of 1.15 by the looks of it and will probably be included in the next 1.14.x release.

**Comment by JetSetIlly** [comment]
Yeah. This is the fix for the compiler bug. Subject to review but I think it's okay.

https://go-review.googlesource.com/c/go/+/226197/

Should be in 1.15 and back-ported to 1.14.x

**Comment by pbarker** [comment]
nice, added the fix here https://github.com/aunum/gold/pull/4
