### ISSUE TITLE
Taxi q experiment panics

### ISSUE THREAD

**Issue by pmalek** [aunum/gold#5]
Using `go1.14.1` with https://github.com/aunum/gold/commit/8dedf68d0993b8fb4355edfc560c1567ea9fb80c I get a panic in taxi experiment:

```
go run -trimpath ./pkg/v1/agent/q/experiments/taxi/main.go
ℹ  tracking data in /var/folders/zy/lzyp__pd7vx6762s5jcgkkl80000gn/T/stats.104998610.json
ℹ  connecting to existing container "stupefied_taussig"
✔  connected to server "gym"
✔  created env: f07159db-890d-45ca-a295-aa9e383507de
ℹ  serving agent api/ui on http://localhost:39421
ℹ  running for 5000 episodes
✖  rpc error: code = Unknown desc = Exception calling application: 'int' object has no attribute 'ravel'
goroutine 1 [running]:
runtime/debug.Stack(0x75, 0x0, 0x0)
        runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
        runtime/debug/stack.go:16 +0x22
github.com/aunum/log.fatalf(0xc0007e0100, 0x1c76e46, 0x3, 0xc0007e1f28, 0x1, 0x1)
        github.com/aunum/log@v0.0.0-20200321163253-24c356e939b0/log.go:77 +0x11d
github.com/aunum/log.Fatalf(...)
        github.com/aunum/log@v0.0.0-20200321163253-24c356e939b0/log.go:64
github.com/aunum/log.Fatal(0xc0007e1f28, 0x1, 0x1)
        github.com/aunum/log@v0.0.0-20200321163253-24c356e939b0/log.go:109 +0xa3
github.com/aunum/gold/pkg/v1/common/require.NoError(...)
        github.com/aunum/gold/pkg/v1/common/require/require.go:18
main.main()
        command-line-arguments/main.go:36 +0x303
exit status 1
```

**Comment by pbarker** [comment]
ah I think this is because I haven't pushed the new container, let me check

**Comment by pbarker** [comment]
thanks for catching this, new container is pushed, just tested on master. Let me know if you have any trouble

**Comment by pmalek** [comment]
So, I've checked this and I still get the same thing despite updating to https://github.com/aunum/gold/commit/bb713ddf1b77c4274386aecc501e4870e5c5d61c

Should I do something else?

**Comment by pbarker** [comment]
try and remove your docker images, to do all would be `docker rmi $(docker images)` and run it again

**Comment by pmalek** [comment]
I've already remove most of the images that could have been on my machine related to this project but I don't want to remove all the images that I've got.

Do you mind disclosing what concrete images should I be looking for to remove?

**Comment by pbarker** [comment]
yep so you want this image https://hub.docker.com/layers/sphereproject/gym/latest/images/sha256-40a69154793915701befb2b9edcf442edd3e0e6ad485dfe511b3e1d03a79bbe1?context=explore but remove any `sphereproject/gym` images and try and repull

**Comment by pmalek** [comment]
Alright so it started successfully on my Mac and I wanted to be double sure about this so I launched it on my Ubuntu PC and I got this 

```
go run -trimpath ./pkg/v1/agent/q/experiments/taxi/main.go
ℹ  tracking data in /tmp/stats.443086550.json
ℹ  no existing containers found, creating new...
ℹ  creating local server
✔  connected to server "gym"
✔  created env: 2304e38e-c0cf-4935-804d-85f0056fb48b
ℹ  serving agent api/ui on http://localhost:23295
✖  exit status 3
goroutine 1 [running]:
runtime/debug.Stack(0x1d, 0x0, 0x0)
        runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
        runtime/debug/stack.go:16 +0x22
github.com/aunum/log.fatalf(0xc000300100, 0x107a886, 0x3, 0xc00030fe20, 0x1, 0x1)
        github.com/aunum/log@v0.0.0-20200321163253-24c356e939b0/log.go:77 +0x11d
github.com/aunum/log.(*Logger).Fatalf(...)
        github.com/aunum/log@v0.0.0-20200321163253-24c356e939b0/logger.go:42
github.com/aunum/log.(*Logger).Fatal(0x18a9ed0, 0xc00030fe20, 0x1, 0x1)
        github.com/aunum/log@v0.0.0-20200321163253-24c356e939b0/logger.go:74 +0x9e
github.com/aunum/gold/pkg/v1/agent.(*Base).View(0xc00042a000)
        github.com/aunum/gold/pkg/v1/agent/base.go:148 +0x9f
main.main()
        command-line-arguments/main.go:20 +0x19d
exit status 1
```

when

```
docker images | grep sph                                   monkey@pc
sphereproject/gym                 latest                                  82f491fd7f9e        41 minutes ago      1.88GB
```
```

**Comment by pbarker** [comment]
hrm my linux box is down at the moment, let me see if I can spin one up in the cloud an reproduce

**Comment by pbarker** [comment]
what version of ubuntu?

**Comment by pbarker** [comment]
this should be running https://github.com/skratchdot/open-golang/blob/master/open/exec.go#L13 I'm curious if `xgd-open http://google.com` works

**Comment by pmalek** [comment]
> what version of ubuntu?

18.04

**Comment by pmalek** [comment]
Hah, maybe it comes from the fact that I was running this via ssh. Then `xdg-open` would fail (I guess?)

**Comment by pbarker** [comment]
ah that would make sense, so you could comment out https://github.com/aunum/gold/blob/master/pkg/v1/agent/q/experiments/taxi/main.go#L20 which opens the browser and visualizes the agent, you could always add terminal logging if you want to go that route.

**Comment by pmalek** [comment]
Alright, so this seems to be a non-issue. I'd maybe add a log or something helping out the user with a similar issue in the future.

**Comment by pbarker** [comment]
good call added a log message in https://github.com/aunum/gold/pull/8
